<b>LINEAR REGRESSION APPLICATION ON PYTHON

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [4]:
print(x)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]


In [5]:
print(y)

[ 5 20 14 32 22 38]


In [6]:
model = LinearRegression()

In [8]:
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.7158756137479542


In [10]:
print('intercept:', model.intercept_)

intercept: 5.633333333333329


In [11]:
print('slope:', model.coef_)

slope: [0.54]


In [12]:
y_pred = model.predict(x)
print(y_pred)

[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [13]:
y

array([ 5, 20, 14, 32, 22, 38])

In [14]:
from sklearn.metrics import mean_squared_error

In [17]:
mse = mean_squared_error(y, y_pred)

In [18]:
mse

33.75555555555555

In [19]:
rmse = mean_squared_error(y, y_pred, squared=False)
rmse

5.809953145728075

In [20]:
from sklearn.metrics import mean_absolute_error

In [21]:
mae = mean_absolute_error(y,y_pred)
mae

5.466666666666666